# Copyright 2024 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Code extraction utilities for parsing code from LLM completions.

Provides a multi-strategy pipeline for extracting code blocks from freeform text
generated by language models. Strategies include fenced code block parsing
(complete and incomplete), language-specific heuristic extraction, and
user-defined custom extraction logic. Also includes post-processing functions
for cleaning extracted code (removing entry points, wrapping in classes, etc.)
across many programming languages.
"""

import re
from enum import Enum
from typing import List, Literal, Optional, Tuple

import structlog
from pydantic import BaseModel

from sandbox.runners.types import Language

logger = structlog.stdlib.get_logger()

NullableLang = Language | Literal['']


class ExtractedType(Enum):
    """Classification of how a code block was extracted from completion text.

    Attributes:
        Fenced: Extracted from a complete fenced code block (````` ``` ... ``` `````).
        IncompleteFenced: Extracted from a fenced block missing the closing fence.
        Heuristic: Extracted using language-specific heuristic patterns.
        Empty: No code block was found in the completion.
    """

    Fenced = 'fenced'
    IncompleteFenced = 'incomplete_fenced'
    Heuristic = 'heuristic'
    Empty = 'empty'


class CodeBlock(BaseModel):
    """A single extracted code block with associated metadata.

    Attributes:
        priority: Numeric priority used to rank extraction methods. Higher values
            indicate more reliable extraction (e.g., fenced=30, incomplete=20,
            heuristic=10).
        language: The canonical language identifier (e.g., ``'python'``, ``'java'``),
            or empty string if the language could not be determined.
        code: The extracted source code content.
    """

    priority: int
    language: str
    code: str


fenced_code_block_pattern = re.compile(
    # Starting with three backticks and optional language identifier
    r'```([^\n]*)\n'
    r'(.*?)'  # Non-greedy capture of the content
    r'\n\s*```',  # Ending with three backticks
    re.DOTALL | re.MULTILINE)

incomplete_fenced_code_block_pattern = re.compile(
    # Starting with three backticks and optional language identifier
    r'```([^\n]*)\n'
    r'(.*)',  # Greedy capture of the content
    re.DOTALL | re.MULTILINE)

language_to_aliases = {
    'python': ['python', 'Python', 'py', 'Python3', 'python3', 'PY'],
    'cpp': ['cpp', 'c++', 'C++', 'Cpp', 'CPP'],
    'nodejs': ['javascript', 'Javascript', 'JavaScript', 'JS', 'js'],
    'go': ['go', 'Go'],
    'java': ['java', 'Java'],
    'php': ['php'],
    'csharp': ['csharp', 'c#', 'C#'],
    'bash': ['bash', 'Bash', 'BASH', 'sh', 'shell'],
    'typescript': ['typescript'],
    'rust': ['rust', 'Rust', 'rs'],
    'sql': ['sql', 'SQL', 'Sql'],
    'D': ['D', 'd'],
    'julia': ['julia', 'Julia', 'jl'],
    'lua': ['lua', 'Lua'],
    'php': ['php', 'PHP'],
    'perl': ['perl', 'Perl', 'PERL'],
    'R': ['R', 'r'],
    'ruby': ['ruby', 'Ruby'],
    'rust': ['rust', 'Rust', 'rs'],
    'scala': ['scala', 'Scala'],
    'kotlin': ['kotlin', 'Kotlin'],
    'c': ['c', 'C'],
    'html': ['html', 'Html', 'HTML'],
    'javascript': ['javascript', 'Javascript', 'JavaScript'],
    'verilog': ['verilog', 'Verilog', 'VERILOG'],
    'racket': ['racket'],
    'swift': ['swift'],
}

aliases_to_language_tiled = {v: k for k, vs in language_to_aliases.items() for v in vs}


# code extraction
def extract_fenced_code(completion: str) -> List[CodeBlock]:
    """Extract all complete fenced code blocks from a completion string.

    Matches blocks delimited by triple backticks with an optional language
    tag (e.g., ````` ```python ... ``` `````). Each match is returned as a
    ``CodeBlock`` with priority 30.

    Args:
        completion: The raw LLM completion text to search.

    Returns:
        A list of ``CodeBlock`` objects for each complete fenced code block
        found, with language aliases resolved to canonical names.
    """
    code_matches = re.findall(fenced_code_block_pattern, completion)
    results = []
    for m in code_matches:
        lang = aliases_to_language_tiled.get(m[0].strip(), '')
        results.append(CodeBlock(priority=30, language=lang, code=m[1]))
    return results


def adjust_code_block(code_blocks: List[CodeBlock], language: str) -> List[CodeBlock]:
    """Fix code blocks where the language tag appears as the first line of code.

    Some models (notably llama3) produce fenced blocks where the language
    identifier ends up as the first line of the code content rather than
    on the fence line itself. This function detects that pattern and moves
    the language tag to the block's ``language`` field, removing it from
    the code.

    Args:
        code_blocks: The list of code blocks to adjust.
        language: The target canonical language name to check against.

    Returns:
        The adjusted list of code blocks.
    """
    if language == '' or language not in language_to_aliases:
        return code_blocks
    ret = []
    for block in code_blocks:
        lines = block.code.splitlines()
        if block.language == '' and lines and lines[0].strip() in language_to_aliases[language]:
            block.language = language
            block.code = '\n'.join(lines[1:])
        ret.append(block)
    return ret


# code extraction


def extract_incomplete_fenced_code(completion: str) -> List[CodeBlock]:
    """Extract fenced code blocks that are missing the closing triple backticks.

    Matches blocks that start with triple backticks and an optional language
    tag but have no closing fence (e.g., when the LLM output was truncated).
    Uses greedy matching to capture all remaining content. Each match is
    returned as a ``CodeBlock`` with priority 20 (lower than complete fenced).

    Args:
        completion: The raw LLM completion text to search.

    Returns:
        A list of ``CodeBlock`` objects for each incomplete fenced code block
        found.
    """
    code_matches = re.findall(incomplete_fenced_code_block_pattern, completion)
    results = []
    for m in code_matches:
        lang = aliases_to_language_tiled.get(m[0].strip(), '')
        results.append(CodeBlock(priority=20, language=lang, code=m[1]))
    return results


def extract_heuristic_code(completion: str, language: NullableLang = '') -> List[CodeBlock]:
    """Extract code blocks using language-specific heuristic patterns.

    Applies pattern-based extraction when fenced code blocks are not present.
    Currently supports:

    - **Python**: Matches ``def``/``class`` definitions with optional imports.
    - **SQL**: Matches ``SELECT``/``WITH ... AS`` statements.
    - **Bash**: Returns the entire completion as a single code block.

    Each match is returned as a ``CodeBlock`` with priority 10 (lowest).

    Args:
        completion: The raw LLM completion text to search.
        language: The target language for heuristic extraction. Only
            ``'python'``, ``'sql'``, and ``'bash'`` are supported; other
            languages return an empty list.

    Returns:
        A list of ``CodeBlock`` objects extracted via heuristics.
    """

    def extract_py(text):
        code = "\n".join([line for line in text.split("\n") if line.strip() != ""]) + "\n"

        pattern_py = "(?:^(?:import|from|#)[^\n]+\n)*" \
            "^(?:def|class) [^\n]+\n" \
            r"(?:\s+[^\n]+\n)+"  # 函数/类实现
        matches = re.findall(pattern_py, code, re.M)
        return matches

    def extract_sql(text):
        code = "\n".join([line for line in text.split("\n") if line.strip() != ""]) + "\n"

        pattern_sql = r"^\s*(?:select|with\s[^\n]+as)[^;]*"
        matches = re.findall(pattern_sql, code, re.M | re.IGNORECASE)
        return matches

    def extract_bash(text):
        code = "\n".join([line for line in text.split("\n") if line.strip() != ""]) + "\n"
        return code

    if language == 'python':
        return [CodeBlock(priority=10, language='python', code=m) for m in extract_py(completion)]
    elif language == 'sql':
        return [CodeBlock(priority=10, language='sql', code=m) for m in extract_sql(completion)]
    elif language == 'bash':
        return [CodeBlock(priority=10, language='bash', code=extract_bash(completion))]
    else:
        return []


def extract_custom_code(completion: str, custom_logic: str) -> List[CodeBlock]:
    """Execute user-provided Python logic to extract code blocks.

    Runs the ``custom_logic`` string as Python code via ``exec()``, providing
    it with a context that includes ``CodeBlock``, the ``completion`` text,
    ``submit_code_blocks`` (a callback to submit extracted blocks), and the
    built-in extraction helpers ``extract_fenced_code`` and
    ``extract_heuristic_code``.

    Args:
        completion: The raw LLM completion text to extract from.
        custom_logic: A string of Python code that calls
            ``submit_code_blocks(list_of_CodeBlock)`` to emit results.

    Returns:
        A list of ``CodeBlock`` objects produced by the custom logic.
    """
    blocks = []

    def submit(cbs):
        for cb in cbs:
            assert isinstance(cb, CodeBlock), 'extrace code type must be class CodeBlock'
            blocks.append(cb)

    context = {
        'CodeBlock': CodeBlock,
        'completion': completion,
        'submit_code_blocks': submit,
        'extract_fenced_code': extract_fenced_code,
        'extract_heuristic_code': extract_heuristic_code,
    }
    exec(custom_logic, context)
    logger.info(f'got {len(blocks)} custom code blocks')
    return blocks


def filter_language(blocks: List[CodeBlock], language: NullableLang) -> List[CodeBlock]:
    """Filter a list of code blocks to only those matching a given language.

    Args:
        blocks: The list of ``CodeBlock`` objects to filter.
        language: The canonical language name to match, or empty string to
            match blocks with no detected language.

    Returns:
        A new list containing only the blocks whose language matches.
    """
    return [b for b in blocks if b.language == language]


def trim_code_entrypoint(completion: str, language: NullableLang = ''):
    ...


def default_extract_helper(completion: str, language: NullableLang = '', custom_extract_logic: Optional[str] = None):
    """Main extraction entry point: extract the best code block from a completion.

    Applies multiple extraction strategies in order of reliability: fenced code
    blocks (priority 30), heuristic extraction (priority 10), incomplete fenced
    blocks (priority 20), and optionally custom extraction logic. From the
    collected blocks, selects the highest-priority group, then returns the first
    block matching the target language; falls back to the first block of any
    language if no language match is found.

    Args:
        completion: The raw LLM completion text to extract code from.
        language: The target canonical language name to prefer when selecting
            among extracted blocks. Empty string means no language preference.
        custom_extract_logic: Optional Python code string for custom extraction
            (passed to :func:`extract_custom_code`).

    Returns:
        The extracted code string, or empty string if no code was found.
    """
    code_blocks = extract_fenced_code(completion)
    code_blocks += extract_heuristic_code(completion, language)
    code_blocks += extract_incomplete_fenced_code(completion)
    if custom_extract_logic is not None:
        code_blocks += extract_custom_code(completion, custom_extract_logic)
    if len(code_blocks) == 0:
        return ''

    max_priority = max([cb.priority for cb in code_blocks])
    code_blocks = [cb for cb in code_blocks if cb.priority == max_priority]

    target_blocks = filter_language(code_blocks, language)
    if len(target_blocks) > 0:
        return target_blocks[0].code
    return code_blocks[0].code


def remove_entripoints(code, language: NullableLang = ''):
    """Strip common entry point patterns from extracted code.

    Removes language-specific main entry points:

    - **Python**: Removes ``if __name__ == "__main__":`` block and
      ``# Example usage`` sections.
    - **C++**: Removes ``int main()`` and everything after.
    - **Go**: Removes ``package main`` declaration.

    Args:
        code: The source code string to clean.
        language: The canonical language name to determine which patterns
            to remove.

    Returns:
        The code with entry point patterns removed.
    """
    if language == 'python':
        if 'if __name__ == \"__main__\":' in code:
            next_line = code.index('if __name__ == \"__main__\":')
            code = code[:next_line].strip()
    elif language == 'cpp':
        if 'int main()' in code:
            next_line = code.index('int main()')
            code = code[:next_line].strip()
    elif language == 'go':
        # Remove package main
        code = code.replace('package main', '')
    if '# Example usage' in code:
        next_line = code.index('# Example usage')
        code = code[:next_line].strip()
    return code


# compatible function for evals/evals/elsuite/utils/coding_evaluation/utils_coding/extract_code_from_freeform_completion
def extract_code_from_freeform_completion(completion: str,
                                          language: NullableLang = '',
                                          first_block_only=False,
                                          **kwargs) -> Tuple[str, str]:
    """Legacy v1 extraction: extract code from freeform LLM completion with post-processing.

    Tries fenced blocks first, then incomplete fenced, then heuristic extraction.
    Applies language-specific post-processing including:

    - **Python**: Optionally removes assert statements; strips ``__main__`` blocks.
    - **C++**: Strips ``int main()`` and everything after.
    - **Java**: Wraps code in ``class Solution``, handles imports from declaration.
    - **Go**: Removes ``package main``.

    Args:
        completion: The raw LLM completion text.
        language: Target canonical language name.
        first_block_only: If True, use only the first extracted code block
            instead of concatenating all blocks.
        **kwargs: Additional options including:
            - ``is_fewshot_task`` (bool): Select first matching block for few-shot tasks.
            - ``exactly_match`` (bool): Drop blocks with non-matching language tags.
            - ``code_block_idx`` (int): Select a specific block by index.
            - ``remove_asserts`` (bool): Remove top-level assert statements (Python).
            - ``entry_point`` (str): Function name for Java class wrapping.
            - ``declaration`` (str): Import declarations to prepend (Java).

    Returns:
        A tuple of ``(code, extracted_type)`` where ``extracted_type`` is
        one of the ``ExtractedType`` enum values as a string.
    """
    extracted_type = ExtractedType.Empty  # initialize to empty case

    # step1. match the complete fenced block
    code_blocks = extract_fenced_code(completion)

    if kwargs.get('is_fewshot_task') is True:
        first_sp_block_idx = next((i for i, block in enumerate(code_blocks) if block.language == language), -1)
        first_un_block_idx = next((i for i, block in enumerate(code_blocks) if block.language == ''), -1)
        first_block_idx = first_un_block_idx if first_sp_block_idx == -1 else first_sp_block_idx
        if first_block_idx != -1:
            code_blocks = code_blocks[:first_block_idx + 1]
            code_blocks = code_blocks[:first_block_idx + 1]
        logger.debug(f'select first code block for fewshot task: {code_blocks}')

    # drop the blocks which the language tag different with target programming language
    if kwargs.get('exactly_match') == True and language:
        other_tag = set(sum([v for k, v in language_to_aliases.items() if k != language], []))
        code_blocks = [b for b in code_blocks if b.language not in other_tag]

    if code_blocks:
        extracted_type = ExtractedType.Fenced

    # step2. if no complete fenced block found, then match the incomplete fenced block
    if len(code_blocks) == 0:
        code_blocks = extract_incomplete_fenced_code(completion)
        if code_blocks:
            extracted_type = ExtractedType.IncompleteFenced

    # step3. if no incomplete fenced block found, try heuristic method to extract code
    if len(code_blocks) == 0:
        code_blocks = extract_heuristic_code(completion, language)
        if code_blocks:
            extracted_type = ExtractedType.Heuristic

    if kwargs.get('code_block_idx') is not None:
        try:
            completion = code_blocks[kwargs['code_block_idx']].code.replace('\r', '')
        except:
            completion = ''
    elif first_block_only:
        if code_blocks:
            completion = code_blocks[0].code.replace('\r', '')
        else:
            completion = ''
    else:
        completion = '\n\n'.join([b.code for b in code_blocks]).replace('\r', '')

    if language == 'python':

        if kwargs.get('remove_asserts') is True:
            #remove assert statements
            lines = []
            for line in completion.split('\n'):
                if line.startswith('assert '):
                    continue
                else:
                    lines.append(line)
            completion = '\n'.join(lines)

        if 'if __name__ == \"__main__\":' in completion:
            next_line = completion.index('if __name__ == \"__main__\":')
            completion = completion[:next_line].strip()
    elif language == 'cpp':
        if 'int main()' in completion:
            next_line = completion.index('int main()')
            completion = completion[:next_line].strip()
    elif language == 'java':
        # Add class Solution before signature
        if 'public class Main {\n' in completion:
            completion = completion.replace('public class Main {\n', 'class Solution {\n')
            completion = completion.replace('public static void main(String[] args)', '')
        if 'class Solution' not in completion:
            for line in completion.split('\n'):
                if kwargs.get('entry_point') and kwargs.get('entry_point') in line:
                    completion = completion.replace(line, 'class Solution {\n' + line)
                    completion += '\n}'
                    break
        # Add import statements
        for line in kwargs.get('declaration', '').split('\n'):
            if 'import' in line:
                completion = line + '\n' + completion
    elif language == 'go':
        # Remove package main
        completion = completion.replace('package main', '')
    if '# Example usage' in completion:
        next_line = completion.index('# Example usage')
        completion = completion[:next_line].strip()

    return (completion, extracted_type.value)


def extract_code_from_freeform_completion_v2(completion: str,
                                             language: NullableLang = '',
                                             first_block_only=False,
                                             no_removal=False,
                                             **kwargs) -> Tuple[str, str]:
    """Enhanced v2 extraction: extract code from freeform LLM completion.

    Improved version that handles llama3 formatting quirks (adjacent empty
    fenced blocks, language tag as first code line). Applies
    :func:`postprocess_completion_v2` for language-specific cleanup unless
    ``is_ut`` is True (unit test mode skips post-processing).

    Args:
        completion: The raw LLM completion text.
        language: Target canonical language name.
        first_block_only: If True, use only the first extracted code block.
        no_removal: If True, skip certain removal steps in post-processing
            (e.g., preserving ``package main`` in Go).
        **kwargs: Additional options including:
            - ``inner_function_only`` (bool): Extract only the inner function
              body (used for C#, Java).
            - ``is_ut`` (bool): If True, skip post-processing (unit test mode).
            - ``is_fewshot_task`` (bool): Select first matching block for
              few-shot tasks.
            - ``exactly_match`` (bool): Keep only blocks matching the target
              language tag.
            - ``code_block_idx`` (int): Select a specific block by index.
            - ``remove_asserts`` (bool): Remove assert statements (Python).
            - ``entry_point`` (str): Function name for Java class wrapping.
            - ``declaration`` (str): Import declarations to prepend (Java).

    Returns:
        A tuple of ``(code, extracted_type)`` where ``extracted_type`` is
        one of the ``ExtractedType`` enum values as a string.
    """
    completion_bk = completion  # backup the input
    extracted_type = ExtractedType.Empty  # initialize to empty case

    # step0. preprocess
    completion = completion.replace('```\n```', '```')  # solve llama3 error format

    # step1. match the complete fenced block
    code_blocks = extract_fenced_code(completion)
    code_blocks = adjust_code_block(code_blocks, language)  # solve llama3 error format

    if kwargs.get('is_fewshot_task') is True:
        first_sp_block_idx = next((i for i, block in enumerate(code_blocks) if block.language == language), -1)
        first_un_block_idx = next((i for i, block in enumerate(code_blocks) if block.language == ''), -1)
        first_block_idx = first_un_block_idx if first_sp_block_idx == -1 else first_sp_block_idx
        if first_block_idx != -1:
            code_blocks = code_blocks[:first_block_idx + 1]
            code_blocks = code_blocks[:first_block_idx + 1]
        logger.debug(f'select first code block for fewshot task: {code_blocks}')

    # drop the blocks which the language tag different with target programming language
    if kwargs.get('exactly_match') == True and language:
        target_tag = language_to_aliases.get(language, [])
        code_blocks = [b for b in code_blocks if b.language in target_tag]

    if code_blocks:
        extracted_type = ExtractedType.Fenced

    # step2. if no complete fenced block found, then match the incomplete fenced block
    if len(code_blocks) == 0:
        code_blocks = extract_incomplete_fenced_code(completion)
        if code_blocks:
            extracted_type = ExtractedType.IncompleteFenced

    # step3. if no incomplete fenced block found, try heuristic method to extract code
    if len(code_blocks) == 0:
        code_blocks = extract_heuristic_code(completion, language)
        if code_blocks:
            extracted_type = ExtractedType.Heuristic

    if kwargs.get('code_block_idx') is not None:
        try:
            completion = code_blocks[kwargs['code_block_idx']].code.replace('\r', '')
        except:
            completion = ''
    elif first_block_only:
        if code_blocks:
            completion = code_blocks[0].code.replace('\r', '')
        else:
            completion = ''
    else:
        completion = '\n\n'.join([b.code for b in code_blocks]).replace('\r', '')

    is_ut = kwargs.get('is_ut') == True
    if not is_ut:
        completion = postprocess_completion_v2(completion, language, no_removal, completion_bk, **kwargs)

    if '# Example usage' in completion:
        next_line = completion.index('# Example usage')
        completion = completion[:next_line].strip()

    return (completion, extracted_type.value)


def postprocess_completion_v2(completion: str, language: str, no_removal: bool, completion_bk: str, **kwargs) -> str:
    """Apply language-specific post-processing to extracted code.

    Cleans up extracted code based on the target language:

    - **Python**: Removes ``__main__`` blocks; optionally removes asserts.
    - **C/C++**: Removes ``int main()`` and everything after.
    - **Java**: Wraps in ``class Solution``, handles imports, optionally
      extracts inner function body.
    - **Go**: Removes ``package main`` (unless ``no_removal``), removes
      ``func main``.
    - **Scala**: Extracts body from ``object X { ... }`` wrapper.
    - **Verilog**: Extracts content between module ports and ``endmodule``.
    - **C#**: Optionally extracts inner function body.
    - **Kotlin**: Removes ``fun main`` function.

    Args:
        completion: The extracted code string to post-process.
        language: The canonical language name.
        no_removal: If True, skip certain removal steps (e.g., Go's
            ``package main``).
        completion_bk: The original unprocessed completion, used as fallback
            when extraction yields empty results (Verilog).
        **kwargs: Additional options (``inner_function_only``, ``remove_asserts``,
            ``entry_point``, ``declaration``).

    Returns:
        The post-processed code string.
    """
    inner_function_only = kwargs.get('inner_function_only') == True

    if language == 'python':
        lines = completion.splitlines()
        idx = None
        for i, line in enumerate(lines):
            if '__name__' in line and '__main__' in line:
                idx = i
                break
        if idx is not None:
            lines = lines[:idx]
        completion = '\n'.join(lines)

        if kwargs.get('remove_asserts') is True:
            lines = []
            for line in completion.splitlines():
                if not line.startswith('assert '):
                    lines.append(line)
            completion = '\n'.join(lines)

    elif language in ['cpp', 'c']:
        if 'int main()' in completion:
            next_line = completion.index('int main()')
            completion = completion[:next_line].strip()
    elif language == 'java':
        if inner_function_only:
            pattern = r"(public|private|protected)\s+(static\s+)(.*?)\((.*?)\)\s*{"
            body = find_inner_function_body(pattern, completion)
            if body is not None:
                completion = completion[body[0]:body[1]]
        else:
            # Add class Solution before signature
            if 'public class Main {\n' in completion:
                completion = completion.replace('public class Main {\n', 'class Solution {\n')
                completion = completion.replace('public static void main(String[] args)', '')
            # remove `public` of class `Solution`
            if 'public class Solution {' in completion:
                completion = completion.replace('public class Solution {', 'class Solution {')
            if 'class Solution' not in completion:
                for line in completion.split('\n'):
                    if kwargs.get('entry_point') and kwargs.get('entry_point') in line:
                        completion = completion.replace(line, 'class Solution {\n' + line)
                        completion += '\n}'
                        break
            # Add import statements
            for line in kwargs.get('declaration', '').split('\n'):
                if 'import' in line:
                    completion = line + '\n' + completion
    elif language == 'go':
        # 一般来说移除 `package main` 语句，部分数据集不要做移除，例如 mbxp
        if no_removal == False:
            completion = completion.replace('package main', '')

        # Delete the main function from completion, if exists.
        pattern = r"func\s+main\(.*?\)\s*{"
        body = find_inner_function_body(pattern, completion)
        if body is not None:
            completion = completion[:body[0]] + completion[body[1]:]
    elif language == 'scala':
        # 提取出包裹在 object X { ... } 中的部分，一般来说是个函数
        pat = r"object\s+\w+(\s+extends\s+\w+)?\s*\n*\{(.*)\}"
        r = re.findall(pat, completion, re.DOTALL | re.MULTILINE)
        if r:
            completion = r[0][1]
    elif language == 'verilog':
        # 提取出在 module X (X, X); .... endmodule 中分号到endmodule之间的内容，包括endmodule
        pat = r'module\s+\w+\s+\((.*?)\);(.*?)endmodule'
        r = re.findall(pat, completion, re.DOTALL | re.MULTILINE)
        if r:
            completion = r[0][1] + '\nendmodule'
        if completion == "":
            # if we cannot extract any code block, return the unacted input
            completion = completion_bk
    elif language == 'csharp':
        # 提取 class 内 function body 部分
        if inner_function_only:
            pattern = r"(public|private|protected|internal)\s+(static\s+)(.*?)\((.*?)\)\s*{"
            body = find_inner_function_body(pattern, completion)
            if body is not None:
                completion = completion[body[0]:body[1]]
    elif language == 'kotlin':
        # Delete the main function from completion, if exists.
        pattern = r"fun\s+main\(.*?\)\s*{"
        body = find_inner_function_body(pattern, completion)
        if body is not None:
            completion = completion[:body[0]] + completion[body[1]:]
    return completion


def trim_till_first_function(code, language):
    """Find the first function definition in code and return only that function.

    Locates the first function using language-specific regex patterns, then
    determines the function's full extent using bracket matching (for Go and
    TypeScript) or indentation analysis (for Python).

    Supported languages: ``'python'``, ``'golang'``/``'go'``, ``'typescript'``.

    Args:
        code: The source code string to search.
        language: The language of the code. Must be one of the supported
            languages.

    Returns:
        The source code from the beginning of the file through the end of
        the first function, or empty string if no function is found.

    Raises:
        ValueError: If the language is not supported.
    """
    # Regex patterns to find the start of a function
    if language == 'python':
        pattern = r'\bdef\s+\w+\s*\((?:[^()]|\n)*\)\s*->?\s*[\w\[\],\s]*:'
        # Python uses indentation, not brackets
        open_bracket, close_bracket = ':', None
    elif language in ['golang', 'go']:
        pattern = r'\bfunc\s+\w+\s*\([^)]*\)\s*(\[\w+\]|\*?\w*)?\s*{'
        open_bracket, close_bracket = '{', '}'
    elif language == 'typescript':
        pattern = r'\bfunction\s+\w+\s*\([^)]*\)\s*[:\w\s]*{'
        open_bracket, close_bracket = '{', '}'
    else:
        raise ValueError("Unsupported language")

    # Find the start of the first function
    match = re.search(pattern, code)
    if not match:
        return ''  # No function found

    if close_bracket:
        # Count brackets to find the end
        start_index = match.start()
        end_index = start_index
        bracket_count = 0
        in_string = False
        escape = False
        while end_index < len(code):
            char = code[end_index]
            if char in ('"', "'"):
                # Handle strings
                if not in_string:
                    in_string = True
                    string_delimiter = char
                elif char == string_delimiter and not escape:
                    in_string = False
            elif not in_string:
                if char == open_bracket:
                    bracket_count += 1
                elif char == close_bracket:
                    bracket_count -= 1
                    if bracket_count == 0:
                        break
            # Handle escape characters in strings
            escape = char == '\\' and not escape
            end_index += 1

        return code[:end_index + 1]
    else:
        # For Python, use indentation levels
        lines = code[match.end():].splitlines()
        first_line_indent = len(lines[0]) - len(lines[0].lstrip())
        function_code = code[:match.end()]
        for line in lines[1:]:
            indent = len(line) - len(line.lstrip())
            if line.strip() and indent <= first_line_indent:
                break
            function_code += '\n' + line

        return function_code


def find_java_public_class_name(java_code: str) -> str:
    """Find the name of the public class in a Java source code string.

    Args:
        java_code: A string containing Java source code.

    Returns:
        The name of the public class if found, or ``None`` if no public
        class declaration is present.
    """
    pattern = r'\bpublic\s+(abstract\s+|final\s+)?class\s+(\w+)'
    match = re.search(pattern, java_code)
    if match:
        return match.group(2)
    else:
        return None


def find_inner_function_body(signature_pattern: str, completion: str) -> Optional[Tuple[int, int]]:
    """Find the start and end indices of a function body inside a class block.

    Uses bracket counting to locate the matching closing brace after the
    function signature. Used for languages like C# and Java.

    Args:
        signature_pattern: Regex pattern matching the function signature up to
            and including the opening ``{``.
        completion: The source code string to search.

    Returns:
        A ``(start, end)`` tuple of character indices spanning the full
        function (signature through closing brace), or ``None`` if no match.
    """
    matches = re.search(signature_pattern, completion, re.DOTALL | re.MULTILINE)
    if matches is None:
        return None
    brackets_count = 1
    idx = None
    for idx in range(matches.end(), len(completion)):
        if completion[idx] == '{':
            brackets_count += 1
        elif completion[idx] == '}':
            brackets_count -= 1

        if brackets_count == 0:
            break
    if idx is None or brackets_count != 0:
        return None
    # body = completion[matches.start():idx + 1]
    return (matches.start(), idx + 1)
