model:
  path: "Qwen/Qwen2.5-Math-7B-Instruct"
  tp_size: null
  max_model_len: 4096
  enable_thinking: false
data:
  names: "all"
  add_open_think: false
wandb:
  enable: true
  project: "math_evals"
